# Cold email sender

In [ ]:
import pandas as pd 
import re
import os 
import base64
from email.mime.text import MIMEText
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
SCOPES = ['https://www.googleapis.com/auth/gmail.send']

cred_path = "/home/question/Documents/CS/VS_Code/cold_email/credentials.json"

flow = InstalledAppFlow.from_client_secrets_file(cred_path, SCOPES)
creds = flow.run_local_server(port=0)

service = build('gmail', 'v1', credentials=creds)
print("Connected!")

Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=834579829689-vpkta3laomidrfae1609aajp3a8rtrrh.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A60905%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgmail.send&state=I84iv0ToLitv0pZe4FaKmYIjblW8Mw&code_challenge=HJr_chunyCMOfZWVSYmj_23UnaC-ma326P3IReYX164&code_challenge_method=S256&access_type=offline
Connected!

In [16]:
emails_df = pd.read_excel("/home/question/Documents/CS/VS_Code/cold_email/hr_email_list.xlsx")
emails_df.head()

                            Emails
0  Ioana-Andreea.DOBRE@cegedim.com
1         g.dorado@meetic-corp.com
2          s.waquet@geser-best.com
3     l.salvador@mbs-education.com
4             ltomaszewski@hays.pl

In [39]:
emails_df["Domain"] = emails_df["Emails"].str.extract(r"@(.+)\.")
emails_df["Country"] = emails_df["Emails"].str.split('.').str[-1]
emails_df.head()

                            Emails         Domain Country
0  Ioana-Andreea.DOBRE@cegedim.com        cegedim     com
1         g.dorado@meetic-corp.com    meetic-corp     com
2          s.waquet@geser-best.com     geser-best     com
3     l.salvador@mbs-education.com  mbs-education     com
4             ltomaszewski@hays.pl           hays      pl

In [42]:
print(emails_df["Domain"].value_counts())

Domain
gmail       79
hotmail     11
live         4
yahoo        3
cegedim      2
            ..
adentis      1
elogenh2     1
qonto        1
whize        1
stakha       1
Name: count, Length: 81, dtype: int64

In [ ]:
# List of domains you want to keep
allowed_domains = ["gmail", "outlook", "live", "yahoo"]

# Filter the DataFrame
filtered_df = emails_df[(emails_df["Domain"].isin(allowed_domains)) & (emails_df["Country"] != "com")]

print(filtered_df)

TypeError: bad operand type for unary ~: 'list'

In [ ]:
import base64
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

def send_email_with_pdf(service, to, subject, body, pdf_path):
    message = MIMEMultipart()
    message['to'] = to
    message['subject'] = "Data Analyst Available – Python, Power BI, SQL | Daksh Sankhla"
    
    # Email body
    message.attach(MIMEText(body, 'plain'))
    
    # Attach PDF
    with open(pdf_path, 'rb') as f:
        part = MIMEBase('application', 'octet-stream')
        part.set_payload(f.read())
    
    encoders.encode_base64(part)
    part.add_header('Content-Disposition', f'attachment; filename="/home/question/Downloads/Daksh Professional CV.pdf"')
    message.attach(part)
    
    raw = base64.urlsafe_b64encode(message.as_bytes()).decode()
    service.users().messages().send(userId='me', body={'raw': raw}).execute()

# Usage
send_email_with_pdf(service, 'petrifiedlightning.spacejunk@gmail.com', 'Hello', 
                    'See attached!', '/home/question/Downloads/Daksh Professional CV.pdf')

In [ ]:
email_subject = "Data Analyst Available – Python, Power BI, SQL | Daksh Sankhla"

email_body =

In [62]:
send_email_with_pdf(service, 'petrifiedlightning.spacejunk@gmail.com', email_subject, 
                    email_text,'/home/question/Downloads/Daksh Professional CV.pdf' )

In [ ]:
send_email_with_pdf(service, 'petrifiedlightning.spacejunk@gmail.com', 'Hello', 
                    'See attached!', '/home/question/Downloads/Daksh Professional CV.pdf')